### ISSUE TITLE
Coprocessor support ENUM / SET  Roadmap

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/tikv#1]
Issue: https://github.com/tikv/tikv/issues/8605
RFC: https://github.com/tikv/rfcs/pull/57

## Roadmap

- [ ] Update `FieldTypeAccessor` to fetch enum/set info from `ColumnInfo`
- [ ] Update eval_type to add enum/set type
- [ ] Implement Enum/Set
- [ ] Implement ChunkedVecEnum/ChunkedVecSet
- [ ] Update ScalarValue / VectorValue
- [ ] Implmement Vectorized Functions
